name: FinGrip
options:
  bundleIdPrefix: com.fingrip
  deploymentTarget:
    iOS: 17.0
  useBaseInternationalization: true
targets:
  FinGrip:
    type: application
    platform: iOS
    sources:
      - path: FinGrip
        includes:
          - "**/*.swift"
          - "**/*.strings"
          - "**/*.lproj/**"
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: FinGrip/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.fingrip.app
        DEVELOPMENT_ASSET_PATHS: ["FinGrip/Preview Content"]
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
        SWIFT_VERSION: 5.0
        ENABLE_TESTABILITY: YES
        DEVELOPMENT_TEAM: ""
        CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
    info:
      path: FinGrip/Info.plist
      properties:
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UILaunchStoryboardName: LaunchScreen
        CFBundleLocalizations:
          - en
          - pl
        CFBundleDevelopmentRegion: en
    resources:
      - path: FinGrip/Resources
        type: group
        excludes:
          - "**/.DS_Store"
        createIntermediateGroups: true
