name: FinGrip
options:
  bundleIdPrefix: com.fingrip
  deploymentTarget:
    iOS: 17.0
targets:
  FinGrip:
    type: application
    platform: iOS
    sources:
      - FinGrip
    settings:
      base:
        INFOPLIST_FILE: FinGrip/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.fingrip.app
    info:
      path: FinGrip/Info.plist
      properties:
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UILaunchStoryboardName: LaunchScreen
